AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "wolfeidau: API server powered by HTTP API."

Parameters:
  AppName:
    Type: String
    Description: The name of the application.

  Stage:
    Type: String
    Description: The stage of development, e.g., dev, test, prod.
    Default: dev

  Branch:
    Type: String
    Description: The branch used to deploy.
    Default: master

  LogRetention:
    Type: Number
    Default: 14

  FirehoseImportStreamName:
    Description: "Firehose analytics event import stream name."
    Type: String

Outputs:
  APIFunctionLogGroup:
    Description: The log group which stores api lambda logs.
    Value: !Ref APIFunctionLogGroup
  APIFunctionUrl:
    Description: The API Function URL.
    Value: !GetAtt APIFunctionUrl.FunctionUrl
  APIFunctionArn:
    Description: The API Function ARN.
    Value: !GetAtt APIFunctionUrl.FunctionArn

Globals:
  Function:
    Runtime: provided.al2023
    Architectures:
      - arm64
    Timeout: 3
    MemorySize: 128
    Tracing: Active
    Environment:
      Variables:
        STAGE: !Ref Stage
        BRANCH: !Ref Branch

Resources:
  APIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../dist/analytics-api-lambda.zip
      Handler: bootstrap
      FunctionUrlConfig:
        AuthType: AWS_IAM
        InvokeMode: RESPONSE_STREAM
      Environment:
        Variables:
          DELIVERY_STREAM_NAME: !Ref FirehoseImportStreamName
      Policies:
        - FirehoseWritePolicy:
            DeliveryStreamName: !Ref FirehoseImportStreamName

  APIFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${APIFunction}"
      RetentionInDays: !Ref LogRetention

  APIFunctionFunctionUrlParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/config/${Stage}/${Branch}/${AppName}/analytics_api_function_url"
      Type: String
      Value: !GetAtt APIFunctionUrl.FunctionUrl

  APIFunctionFunctionArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/config/${Stage}/${Branch}/${AppName}/analytics_api_function_arn"
      Type: String
      Value: !GetAtt APIFunctionUrl.FunctionArn
