AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "wolfeidau: Analytics event glue database which acts as a datalake for analytics event data."

Parameters:
  AppName:
    Type: String
    Description: The name of the application.

  Stage:
    Type: String
    Description: The stage of development, e.g., dev, test, prod.
    Default: dev
    AllowedPattern: "[a-z]*"

  Branch:
    Type: String
    Description: The branch used to deploy.
    Default: master
    AllowedPattern: "[a-z]*"

  DatabaseName:
    Type: String
    Default: analytics_events
    AllowedPattern: "[a-z_]*"

Outputs:
  AnalyticsDatabase:
    Value: !Ref AnalyticsDatabase


Resources:
  AnalyticsDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        # Using a name compatible with Apache Hive (alphanumeric and underscore characters) since the intent is to use this database with Athena.
        # Names auto generated by CloudFormation do not follow this pattern.
        # See https://docs.aws.amazon.com/athena/latest/ug/create-table.html for more details
        Name: !Sub ${DatabaseName}_${Stage}_${Branch}
        Description: Analytics events database

  AnalyticsDatabaseNameParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/config/${Stage}/${Branch}/${AppName}/analytics_glue_database"
      Type: "String"
      Value: !Ref AnalyticsDatabase
      Description: "Analytics events glue database name"
